# Book settings
title: Processing and Visualizing By the People Transcription Data
author: Dave Durden and Madeline Goebel
html:
    extra_footer: |
        <header class="loc-header">
            <div class="loc-logo">
                <a href="https://www.loc.gov/"><img src="_static/LOC_Logo_horiz_inv.png" alt="The Library of Congress logo" title="Go to the Library of Congress homepage" /></a>
            </div>
            <div class="project-description">
                <p>This Python tutorial demonstrates how to process and visualize <a href="https://crowd.loc.gov/">By the People</a> transcription data using natural language processing. <a href="https://github.com/libraryOfCongress/btp-data" class="button small">View the code</a></p>
            </div>
        </header>
        <footer class="loc-footer">
            <p>This Python tutorial demonstrates how to process and visualize <a href="https://crowd.loc.gov/">By the People</a> transcription data using natural language processing.</p>
            <ul class="loc-footer-nav-list">
                <li><a href="https://github.com/libraryOfCongress/btp-data">Source code</a></li>  
                <li><a href="https://www.loc.gov/">The Library of Congress</a></li>
                <li><a href="https://loc.gov/legal">Privacy Policy</a></li>
                <li><a href="https://www.loc.gov/accessibility/">Accessibilty</a></li>
                <li><a href="https://docs.github.com/en/site-policy/privacy-policies/github-privacy-statement">Github Privacy Statement</a></li>
                <li><a href="https://creativecommons.org/publicdomain/zero/1.0/">License</a></li>
                <li><a href="https://ask.loc.gov/crowd">Contact</a></li>
            </ul>
        </footer>

# The following values assume that you are executing the notebooks yourself before you build
# Re-execution of notebooks are turned off since these scripts take a very long time to (re-)build
# Look here for more options: https://jupyterbook.org/en/stable/content/execute.html
execute:
  execute_notebooks: 'off'
  stderr_output: remove